export const developerTypes = [
    "Front-end Developer",
    "Back-end Developer",
    "Full-stack Developer",
    "Mobile App Developer",
    "Web Developer",
    "Game Developer",
    "UI/UX Designer",
    "DevOps Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Database Administrator",
    "Cloud Solutions Architect",
    "Blockchain Developer",
    "Embedded Systems Developer",
    "Quality Assurance Engineer",
    "Systems Administrator",
    "Network Engineer",
    "Security Analyst",
    "AR/VR Developer",
    "IoT Developer",
    "AI Developer",
    "Bioinformatics Developer",
    "Firmware Engineer",
    "Quantum Computing Developer",
    "Robotics Engineer",
    "Natural Language Processing (NLP) Engineer",
    "Big Data Engineer",
    "Front-end Designer",
    "Back-end Architect",
    "Game Artist",
    "Test Automation Engineer",
    "Cybersecurity Specialist",
  ];

  export const devTypesValLab = [
    { value: "Front-end Developer", label: "Front-end Developer" },
    { value: "Back-end Developer", label: "Back-end Developer" },
    { value: "Full-stack Developer", label: "Full-stack Developer" },
    { value: "Mobile App Developer", label: "Mobile App Developer" },
    { value: "Web Developer", label: "Web Developer" },
    { value: "Game Developer", label: "Game Developer" },
    { value: "UI/UX Designer", label: "UI/UX Designer" },
    { value: "DevOps Engineer", label: "DevOps Engineer" },
    { value: "Data Scientist", label: "Data Scientist" },
    { value: "Machine Learning Engineer", label: "Machine Learning Engineer" },
    { value: "Database Administrator", label: "Database Administrator" },
    { value: "Cloud Solutions Architect", label: "Cloud Solutions Architect" },
    { value: "Blockchain Developer", label: "Blockchain Developer" },
    { value: "Embedded Systems Developer", label: "Embedded Systems Developer" },
    { value: "Quality Assurance Engineer", label: "Quality Assurance Engineer" },
    { value: "Systems Administrator", label: "Systems Administrator" },
    { value: "Network Engineer", label: "Network Engineer" },
    { value: "Security Analyst", label: "Security Analyst" },
    { value: "AR/VR Developer", label: "AR/VR Developer" },
    { value: "IoT Developer", label: "IoT Developer" },
    { value: "AI Developer", label: "AI Developer" },
    { value: "Bioinformatics Developer", label: "Bioinformatics Developer" },
    { value: "Firmware Engineer", label: "Firmware Engineer" },
    { value: "Quantum Computing Developer", label: "Quantum Computing Developer" },
    { value: "Robotics Engineer", label: "Robotics Engineer" },
    { value: "Natural Language Processing (NLP) Engineer", label: "Natural Language Processing (NLP) Engineer" },
    { value: "Big Data Engineer", label: "Big Data Engineer" },
    { value: "Front-end Designer", label: "Front-end Designer" },
    { value: "Back-end Architect", label: "Back-end Architect" },
    { value: "Game Artist", label: "Game Artist" },
    { value: "Test Automation Engineer", label: "Test Automation Engineer" },
    { value: "Cybersecurity Specialist", label: "Cybersecurity Specialist" },
  ];