export const developerTypes = [
    "Front-end Developer",
    "Back-end Developer",
    "Full-stack Developer",
    "Mobile App Developer",
    "Web Developer",
    "Game Developer",
    "UI/UX Designer",
    "DevOps Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Database Administrator",
    "Cloud Solutions Architect",
    "Blockchain Developer",
    "Embedded Systems Developer",
    "Quality Assurance Engineer",
    "Systems Administrator",
    "Network Engineer",
    "Security Analyst",
    "AR/VR Developer",
    "IoT Developer",
    "AI Developer",
    "Bioinformatics Developer",
    "Firmware Engineer",
    "Quantum Computing Developer",
    "Robotics Engineer",
    "Natural Language Processing (NLP) Engineer",
    "Big Data Engineer",
    "Front-end Designer",
    "Back-end Architect",
    "Game Artist",
    "Test Automation Engineer",
    "Cybersecurity Specialist",
  ];